### ISSUE TITLE
test_quickstart.py 

### ISSUE THREAD

**Issue by Majoburo** [pmelchior/scarlet2#87]
# Bug Report: `ValueError` in `test_quickstart.py` Due to Unexpected `None` Handling in JAX (Workaround Available) 

## Description
Running `test_quickstart.py` results in a `ValueError: Expected None, got Array([ 5., 34.], dtype=float32)`. This error occurs during a call to `scene.fit()` and is likely related to recent changes in JAX's handling of `None` values in tree structures.

## Steps to Reproduce
1. Set up a clean Conda environment.
2. Install `scarlet2`, `NumPyro`, `Optax`, and other dependencies.
3. Run the `test_quickstart.py` script.

Example commands:
```bash
# Commands to reproduce the issue
conda create -n scarlet2 python
conda activate scarlet2
git clone https://github.com/pmelchior/scarlet2
cd scarlet2
pip install numpyro optax .
python tests/test_quickstart.py
```

## Environment
- **JAX version:** 0.4.35
- **JAXlib version:** 0.4.35

## Error Traceback
```python
python test_quickstart.py
...
ValueError: Expected None, got Array([ 5., 34.], dtype=float32).

In previous releases of JAX, flatten-up-to used to consider None to be a tree-prefix of non-None values. To obtain the previous behavior, you can usually write:
  jax.tree.map(lambda x, y: None if x is None else f(x, y), a, b, is_leaf=lambda x: x is None)
```

## Workaround
Forcing `jax` and `jaxlib` to version `0.4.28` resolves the issue and allows `test_quickstart.py` to run successfully.

**Comment by pmelchior** [comment]
Thanks, Majo. so, somewhere between jax 0.4.30 and 0.4.35, some change was made the breaks our code. Can you post the entire bracktrace, so that we can see which call is causing the problem, please.

**Comment by Majoburo** [comment]
Sure!

```python
python tests/test_quickstart.py
/Users/majoburo/Work/scarlet2/tests/test_quickstart.py:22: UserWarning: A JAX array is being set as static! This can result in unexpected behavior and is usually a mistake to do.
  obs = Observation(data, weights, psf=ArrayPSF(jnp.asarray(psf))).match(model_frame)
Traceback (most recent call last):
  File "/Users/majoburo/Work/scarlet2/tests/test_quickstart.py", line 66, in <module>
    test_quickstart()
    ~~~~~~~~~~~~~~~^^
  File "/Users/majoburo/Work/scarlet2/tests/test_quickstart.py", line 49, in test_quickstart
    scene_ = scene.fit(obs, parameters, max_iter=maxiter, progress_bar=False)
  File "/Users/majoburo/miniconda3/envs/scarlet22/lib/python3.13/site-packages/equinox/_module.py", line 1096, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet22/lib/python3.13/site-packages/scarlet2/scene.py", line 174, in fit
    scene, loss, opt_state, convergence = _make_step(scene, observations, parameters, optim, opt_state,
                                          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     filter_spec=filter_spec)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet22/lib/python3.13/site-packages/equinox/_jit.py", line 275, in __call__
    return self._call(False, args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet22/lib/python3.13/site-packages/equinox/_module.py", line 1096, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet22/lib/python3.13/site-packages/equinox/_jit.py", line 244, in _call
    marker, _, _ = out = self._cached(
                         ~~~~~~~~~~~~^
        dynamic_donate, dynamic_nodonate, static
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/majoburo/miniconda3/envs/scarlet22/lib/python3.13/site-packages/scarlet2/scene.py", line 319, in _make_step
    updates, opt_state = optim.update(grads, opt_state, model)
                         ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet22/lib/python3.13/site-packages/optax/transforms/_combining.py", line 73, in update_fn
    updates, new_s = fn(updates, s, params, **extra_args)
                     ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet22/lib/python3.13/site-packages/optax/_src/base.py", line 330, in update
    return tx.update(updates, state, params)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet22/lib/python3.13/site-packages/scarlet2/scene.py", line 145, in update_fn
    updates = jax.tree_util.tree_map(
        # lambda u, step, param: -step * u if not callable(step) else -step(param,niter) * u,
        lambda u, s, p: -s * u if not callable(s) else -s(p) * u,
        # minus because we want gradient descent
        updates, steps, params)
ValueError: Expected None, got Array([ 5., 34.], dtype=float32).

In previous releases of JAX, flatten-up-to used to consider None to be a tree-prefix of non-None values. To obtain the previous behavior, you can usually write:
  jax.tree.map(lambda x, y: None if x is None else f(x, y), a, b, is_leaf=lambda x: x is None)
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

**Comment by pmelchior** [comment]
OK, found the culprit. In jax 0.4.34, the problematic [change](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-34-october-4-2024) occurred, but it's not clear what exactly is triggering it because there should be no `None`s in these pytrees. Can you try a fresh install with the latest jax and then modify these lines
https://github.com/pmelchior/scarlet2/blob/9360b42c50ee20e364b66916840e50685bde4de7/scarlet2/scene.py#L145-L149
such that l149 reads like this?
```python
updates, steps, params, is_leaf=lambda x: x is None)
 ```

**Comment by Majoburo** [comment]
Still won't work:
```python
$ python tests/test_quickstart.py
/Users/majoburo/Work/scarlet2/tests/test_quickstart.py:22: UserWarning: A JAX array is being set as static! This can result in unexpected behavior and is usually a mistake to do.
  obs = Observation(data, weights, psf=ArrayPSF(jnp.asarray(psf))).match(model_frame)
Traceback (most recent call last):
  File "/Users/majoburo/Work/scarlet2/tests/test_quickstart.py", line 66, in <module>
    test_quickstart()
    ~~~~~~~~~~~~~~~^^
  File "/Users/majoburo/Work/scarlet2/tests/test_quickstart.py", line 49, in test_quickstart
    scene_ = scene.fit(obs, parameters, max_iter=maxiter, progress_bar=False)
  File "/Users/majoburo/miniconda3/envs/scarlet2/lib/python3.13/site-packages/equinox/_module.py", line 1096, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet2/lib/python3.13/site-packages/scarlet2/scene.py", line 174, in fit
    scene, loss, opt_state, convergence = _make_step(scene, observations, parameters, optim, opt_state,
                                          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     filter_spec=filter_spec)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet2/lib/python3.13/site-packages/equinox/_jit.py", line 275, in __call__
    return self._call(False, args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet2/lib/python3.13/site-packages/equinox/_module.py", line 1096, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet2/lib/python3.13/site-packages/equinox/_jit.py", line 244, in _call
    marker, _, _ = out = self._cached(
                         ~~~~~~~~~~~~^
        dynamic_donate, dynamic_nodonate, static
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/majoburo/miniconda3/envs/scarlet2/lib/python3.13/site-packages/scarlet2/scene.py", line 319, in _make_step
    updates, opt_state = optim.update(grads, opt_state, model)
                         ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet2/lib/python3.13/site-packages/optax/transforms/_combining.py", line 73, in update_fn
    updates, new_s = fn(updates, s, params, **extra_args)
                     ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet2/lib/python3.13/site-packages/optax/_src/base.py", line 330, in update
    return tx.update(updates, state, params)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/majoburo/miniconda3/envs/scarlet2/lib/python3.13/site-packages/scarlet2/scene.py", line 145, in update_fn
    updates = jax.tree_util.tree_map(
        # lambda u, step, param: -step * u if not callable(step) else -step(param,niter) * u,
        lambda u, s, p: -s * u if not callable(s) else -s(p) * u,
        # minus because we want gradient descent
        updates, steps, params, is_leaf=lambda x: x is None)
  File "/Users/majoburo/miniconda3/envs/scarlet2/lib/python3.13/site-packages/scarlet2/scene.py", line 147, in <lambda>
    lambda u, s, p: -s * u if not callable(s) else -s(p) * u,
                    ~~~^~~
TypeError: unsupported operand type(s) for *: 'DynamicJaxprTracer' and 'NoneType'
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

**Comment by pmelchior** [comment]
OK, that's interesting because it's telling us that `s` is traced by jax, but `u` is `None`. That's the gradient of the loss function for this parameter. It should never be None. I suspect that optax initialized them this way, so that this problem would only occur on the first iteration.

Can you post your optax version, please.

**Comment by Majoburo** [comment]
optax=0.2.3

**Comment by pmelchior** [comment]
ok, thanks. We're using a optax construct to set up the optimizer schedule, and this is the section that creates the error you report. I need to check if optax has changed, so that our use isn't supported anymore.
